services:
  apios:
    build: 
      context: .
      dockerfile: python-go/Dockerfile
    container_name: apios
    volumes:
      - ./data:/data            # persistent volume for SQLite and other data
      - ./src:/src              # source code
      - ./scripts:/src/scripts  # scripts folder
    depends_on:
      - apios-mongo
      - apios-sqlite
    networks:
      - apios-net
    tty: true
    stdin_open: true

  apios-mongo:
    image: mongo:6
    container_name: apios-mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db    # persistent MongoDB storage
    networks:
      - apios-net
    ports:
      - "27017:27017"

  apios-sqlite:
    image: alpine:latest
    container_name: apios-sqlite
    command: tail -f /dev/null  # keep container alive for exec
    volumes:
      - ./data:/data            # mount same volume as main container
    networks:
      - apios-net
    tty: true
    stdin_open: true

volumes:
  mongo_data:

networks:
  apios-net:
    driver: bridge

